steps:
  # 1. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA', '.']

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:$_DEPLOY_REGION:$_DB_INSTANCE_NAME'
      - '--set-env-vars'
      - 'CLOUD_SQL_CONNECTION_NAME=$PROJECT_ID:$_DEPLOY_REGION:$_DB_INSTANCE_NAME'
      - '--set-env-vars'
      - 'DB_NAME=$_DB_NAME'
      - '--set-env-vars'
      - 'DB_USER=$_DB_USER'
      - '--set-secrets'
      - 'DB_PASS=projects/$PROJECT_ID/secrets/DB_PASS/versions/latest'
      - '--set-secrets'
      - 'OPENAI_API_KEY=projects/$PROJECT_ID/secrets/OPENAI_API_KEY/versions/latest'

substitutions:
  _AR_HOSTNAME: 'us-central1-docker.pkg.dev'
  _AR_REPO: 'rag-quiz-repo'
  _SERVICE_NAME: 'rag-quiz-app'
  _DEPLOY_REGION: 'us-central1'
  _DB_INSTANCE_NAME: 'quiz-sql-instance'
  _DB_NAME: 'quiz_db'
  _DB_USER: 'postgres'